version: 2
jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    working_directory: ~/casto

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      # git pull
      - checkout
        
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle test
  deploy:
    docker:
      # specify OS base to run the steps from
      - image: alpine:3.12
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - run:
          name: Deploy Application to Fly
          command: |
            chmod +x scripts/deploy.sh
            ./scripts/deploy.sh
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            # the test job must pass, before starting the deploy job
            - test
          filters:
            branches:
              # deploy only on branch main
              only: main